---
title: "Lumping Metrics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lumping Metrics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

#> TODO: WRITE THE ENTIRE THING

# Mutual Information

The main goal of the package is to optimize for mutual information.
This is a very abridged outline of what the mutual information means
and how to interpret it.
For a more thorough treatment of information theory, see @cover1991.

The *mutual information* between two random variables expresses how much knowing the value of one of them
reveals about the distribution of the other.
Mathematically, it is expressed as
$$
    I(X; Y) = \sum_{x \in \mathcal{X}} \sum_{y \in \mathcal{Y}} \mathbb{P}(X = x, Y = y) \log \frac{\mathbb{P}(X = x, Y = y)}{\mathbb{P}(X = x) \mathbb{P}( Y = y)}
$$
where, if the logarithm is taken to be natural, we have units of nats.

Another useful quantity from information theory is the *entropy*, which can intuitively be thought of
as the information content of a random variable, or how much 'suprise' the distribution contains.
It has a similar form to the mutual information, being
$$
    H(X) = -\sum_{x \in \mathcal{X}} \mathbb{P}(X = x) \log \mathbb{P}(X = x).
$$

It turns out that, for our application, the mutual information and entropy are identical, since if we take $X$ to be
the distribution of the variable before the lumping and $Y$ to be the distribution after, we have $I(X;Y) = H(Y)$.
This means we get two ways of interpreting optimizing for the mutual information:

* When we regard ourselves as optimizing for the mutual information, we try to find a lumping such that,
    uppon knowing the value of the variable after lumping, we know as much as possible about the value before lumping.
    In other words, it should be possible to recover the original value with as much certainty as possible.
* When we look at the entropy, we are trying to find a lumping that is as disordered as possible.
    This is desirable, since the more disordered the variable is, the more information it contains.


## Heuristics

#> TODO: WRITE

The different heuristics all operate differently and therefore also respond differently to an increase in the
#' size of $m$, the number of levels.

### Smart

#> TODO: document when done

### Largest
Iteratively lumps the smallest level with the largest other level it can be lumped with.
In practice, the algorithm results in one large hard to interpret group and probably ought be avoided.
Has $O\left(m^2\right)$ runtime.

### Other
can be seen as a re-implementation of `forcats::fct_lump_min`, in that
it tries to lump the smallest levels together, with the
added flexibility provided by support for non-complete preference graphs.
Has $O\left(m^2\right)$ runtime.

# Alternative Metrics
## Minimal Lumping
## Surplus

# References